// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum WifiNetworkEventType {
  Discovered = 0,
  Updated = 1,
  Lost = 2,
  Saved = 3,
  Removed = 4,
  Connected = 5,
  Disconnected = 6
}
