// automatically generated by the FlatBuffers compiler, do not modify

export enum WifiNetworkEventType {
  Discovered = 0,
  Updated = 1,
  Lost = 2,
  Saved = 3,
  Removed = 4,
  Connected = 5,
  Disconnected = 6
}
