#pragma once

#define DISABLE_DEFAULT(TypeName) TypeName() = delete
#define DISABLE_COPY(TypeName)                   \
  TypeName(const TypeName&)            = delete; \
  TypeName& operator=(const TypeName&) = delete
#define DISABLE_MOVE(TypeName)              \
  TypeName(TypeName&&)            = delete; \
  TypeName& operator=(TypeName&&) = delete

// Config comes from two places: Kconfig (CONFIG_OPENSHOCK_*, via sdkconfig.h -
// domains, hostname, AP prefix, pins, buffer sizes; see src/Kconfig.projbuild)
// and the generated env header force-included by the build (OPENSHOCK_FW_VERSION,
// OPENSHOCK_FW_BOARD, OPENSHOCK_FW_CHIP, ...; see scripts/gen_env_header.py).
#include "sdkconfig.h"

#ifndef OPENSHOCK_FW_VERSION
#error "OPENSHOCK_FW_VERSION must be defined (generated by scripts/gen_env_header.py)"
#endif

#define OPENSHOCK_FW_CDN_URL(path) "https://" CONFIG_OPENSHOCK_FW_CDN_DOMAIN path

#define OPENSHOCK_GPIO_INVALID -1

// Allow OPENSHOCK_FW_USERAGENT to be overridden through compiler flags; otherwise
// generate a default user agent from the hostname, version, board and chip.
#ifndef OPENSHOCK_FW_USERAGENT
#define OPENSHOCK_FW_USERAGENT CONFIG_OPENSHOCK_FW_HOSTNAME "/" OPENSHOCK_FW_VERSION " (ESP-IDF; " OPENSHOCK_FW_BOARD "; " OPENSHOCK_FW_CHIP "; Espressif)"
#endif

namespace OpenShock::Constants {
  const char* const FW_USERAGENT = OPENSHOCK_FW_USERAGENT;
}  // namespace OpenShock::Constants
