#pragma once

#define DISABLE_DEFAULT(TypeName) TypeName() = delete
#define DISABLE_COPY(TypeName)                   \
  TypeName(const TypeName&)            = delete; \
  TypeName& operator=(const TypeName&) = delete
#define DISABLE_MOVE(TypeName)              \
  TypeName(TypeName&&)            = delete; \
  TypeName& operator=(TypeName&&) = delete

// Config comes from two places: Kconfig (CONFIG_OPENSHOCK_*, via sdkconfig.h -
// domains, hostname, AP prefix, buffer sizes; see components/core/Kconfig.projbuild)
// and the generated board header (OPENSHOCK_FW_BOARD, OPENSHOCK_FW_CHIP, the GPIO
// assignments, ...; see scripts/gen_env_header.py).
#include "sdkconfig.h"

// Board identity and GPIO assignments. Deliberately included here rather than
// force-included into the whole build, so ESP-IDF's own sources never see it.
#include "openshock_board.h"

#ifndef OPENSHOCK_FW_BOARD
#error "OPENSHOCK_FW_BOARD must be defined (generated by scripts/gen_env_header.py)"
#endif
#ifndef OPENSHOCK_FW_CHIP
#error "OPENSHOCK_FW_CHIP must be defined (generated by scripts/gen_env_header.py)"
#endif

#define OPENSHOCK_FW_CDN_URL(path) "https://" CONFIG_OPENSHOCK_FW_CDN_DOMAIN path

#define OPENSHOCK_GPIO_INVALID -1

namespace OpenShock::Constants {
  // Defined in Version.cpp, which is the only translation unit that includes
  // openshock_version.h. Building the string here would have put the firmware version -
  // and so the commit SHA - into every file that includes this header, rebuilding all of
  // them on every commit for a string almost none of them use.
  extern const char* const FW_USERAGENT;
}  // namespace OpenShock::Constants
