// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Configuration

import "strconv"

type OtaUpdateStep byte

const (
	OtaUpdateStepNone        OtaUpdateStep = 0
	OtaUpdateStepUpdating    OtaUpdateStep = 1
	OtaUpdateStepUpdated     OtaUpdateStep = 2
	OtaUpdateStepValidating  OtaUpdateStep = 3
	OtaUpdateStepValidated   OtaUpdateStep = 4
	OtaUpdateStepRollingBack OtaUpdateStep = 5
)

var EnumNamesOtaUpdateStep = map[OtaUpdateStep]string{
	OtaUpdateStepNone:        "None",
	OtaUpdateStepUpdating:    "Updating",
	OtaUpdateStepUpdated:     "Updated",
	OtaUpdateStepValidating:  "Validating",
	OtaUpdateStepValidated:   "Validated",
	OtaUpdateStepRollingBack: "RollingBack",
}

var EnumValuesOtaUpdateStep = map[string]OtaUpdateStep{
	"None":        OtaUpdateStepNone,
	"Updating":    OtaUpdateStepUpdating,
	"Updated":     OtaUpdateStepUpdated,
	"Validating":  OtaUpdateStepValidating,
	"Validated":   OtaUpdateStepValidated,
	"RollingBack": OtaUpdateStepRollingBack,
}

func (v OtaUpdateStep) String() string {
	if s, ok := EnumNamesOtaUpdateStep[v]; ok {
		return s
	}
	return "OtaUpdateStep(" + strconv.FormatInt(int64(v), 10) + ")"
}
