// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Configuration

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WiFiCredentials struct {
	_tab flatbuffers.Table
}

func GetRootAsWiFiCredentials(buf []byte, offset flatbuffers.UOffsetT) *WiFiCredentials {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WiFiCredentials{}
	x.Init(buf, n+offset)
	return x
}

func FinishWiFiCredentialsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWiFiCredentials(buf []byte, offset flatbuffers.UOffsetT) *WiFiCredentials {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WiFiCredentials{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWiFiCredentialsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WiFiCredentials) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WiFiCredentials) Table() flatbuffers.Table {
	return rcv._tab
}

/// ID of the WiFi network credentials, used for referencing the credentials with a low memory footprint
func (rcv *WiFiCredentials) Id() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// ID of the WiFi network credentials, used for referencing the credentials with a low memory footprint
func (rcv *WiFiCredentials) MutateId(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

/// SSID of the WiFi network
func (rcv *WiFiCredentials) Ssid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// SSID of the WiFi network
/// Password of the WiFi network
func (rcv *WiFiCredentials) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Password of the WiFi network
func WiFiCredentialsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func WiFiCredentialsAddId(builder *flatbuffers.Builder, id byte) {
	builder.PrependByteSlot(0, id, 0)
}
func WiFiCredentialsAddSsid(builder *flatbuffers.Builder, ssid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ssid), 0)
}
func WiFiCredentialsAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(password), 0)
}
func WiFiCredentialsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
