// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CaptivePortalConfig } from '../../../open-shock/serialization/gateway/captive-portal-config';
import { OtaInstall } from '../../../open-shock/serialization/gateway/ota-install';
import { ShockerCommandList } from '../../../open-shock/serialization/gateway/shocker-command-list';


export enum GatewayToDeviceMessagePayload {
  NONE = 0,
  ShockerCommandList = 1,
  CaptivePortalConfig = 2,
  OtaInstall = 3
}

export function unionToGatewayToDeviceMessagePayload(
  type: GatewayToDeviceMessagePayload,
  accessor: (obj:CaptivePortalConfig|OtaInstall|ShockerCommandList) => CaptivePortalConfig|OtaInstall|ShockerCommandList|null
): CaptivePortalConfig|OtaInstall|ShockerCommandList|null {
  switch(GatewayToDeviceMessagePayload[type]) {
    case 'NONE': return null; 
    case 'ShockerCommandList': return accessor(new ShockerCommandList())! as ShockerCommandList;
    case 'CaptivePortalConfig': return accessor(new CaptivePortalConfig())! as CaptivePortalConfig;
    case 'OtaInstall': return accessor(new OtaInstall())! as OtaInstall;
    default: return null;
  }
}

export function unionListToGatewayToDeviceMessagePayload(
  type: GatewayToDeviceMessagePayload, 
  accessor: (index: number, obj:CaptivePortalConfig|OtaInstall|ShockerCommandList) => CaptivePortalConfig|OtaInstall|ShockerCommandList|null, 
  index: number
): CaptivePortalConfig|OtaInstall|ShockerCommandList|null {
  switch(GatewayToDeviceMessagePayload[type]) {
    case 'NONE': return null; 
    case 'ShockerCommandList': return accessor(index, new ShockerCommandList())! as ShockerCommandList;
    case 'CaptivePortalConfig': return accessor(index, new CaptivePortalConfig())! as CaptivePortalConfig;
    case 'OtaInstall': return accessor(index, new OtaInstall())! as OtaInstall;
    default: return null;
  }
}
