name: build-compilationdb
description: Builds the compilation database for the firmware for code analysis
inputs:
  board:
    required: true
    description: 'Board name to build'
  version:
    required: true
    description: 'Current firmware version'
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}

    - uses: actions/cache@v4
      with:
        path: |
          ~/.platformio/platforms
          ~/.platformio/packages
          ~/.platformio/.cache
        key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini', 'requirements.txt') }}

    - uses: actions/setup-python@v5
      with:
        cache: 'pip'

    - name: Install python dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Build firmware
      working-directory: .
      shell: bash
      run: pio run -e ${{ inputs.board }} -t compiledb
      env:
        OPENSHOCK_FW_VERSION: ${{ inputs.version }}
        OPENSHOCK_FW_GIT_REF: ${{ github.ref }}
        OPENSHOCK_FW_GIT_COMMIT: ${{ github.sha }}
        OPENSHOCK_FW_BUILD_DATE: ${{ github.event.head_commit.timestamp }}