name: build-compilationdb
description: Builds the compilation database for the firmware for code analysis
inputs:
  version:
    required: true
    description: 'Current firmware version'

runs:
  using: composite
  steps:
    - uses: ./.github/actions/pio-cache
      with:
        env: ci-build

    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        cache: 'pip'

    - name: Install python dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Build firmware
      working-directory: .
      shell: bash
      run: |
        export OPENSHOCK_FW_BUILD_DATE="$(git show -s --format=%cI HEAD 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)"
        pio run -e ci-build -t compiledb
      env:
        OPENSHOCK_FW_VERSION: ${{ inputs.version }}
        OPENSHOCK_FW_GIT_REF: ${{ github.ref }}
        OPENSHOCK_FW_GIT_COMMIT: ${{ github.sha }}