name: build-compilationdb
description: Builds the compilation database for the firmware for code analysis
inputs:
  version:
    required: true
    description: 'Current firmware version'
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      if: ${{ !inputs.skip-checkout }}

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        path: |
          ~/.platformio/platforms
          ~/.platformio/packages
          ~/.platformio/.cache
        key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini', 'requirements.txt') }}

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        cache: 'pip'

    - name: Install python dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Build firmware
      working-directory: .
      shell: bash
      run: pio run -e ci-build -t compiledb
      env:
        OPENSHOCK_FW_VERSION: ${{ inputs.version }}
        OPENSHOCK_FW_GIT_REF: ${{ github.ref }}
        OPENSHOCK_FW_GIT_COMMIT: ${{ github.sha }}
        OPENSHOCK_FW_BUILD_DATE: ${{ github.event.head_commit.timestamp }}