// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EStopConfig {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EStopConfig {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEStopConfig(bb:flatbuffers.ByteBuffer, obj?:EStopConfig):EStopConfig {
  return (obj || new EStopConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEStopConfig(bb:flatbuffers.ByteBuffer, obj?:EStopConfig):EStopConfig {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EStopConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

enabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * The GPIO pin connected to the E-Stop button
 */
gpioPin():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

/**
 * Persistent state of the E-Stop button
 */
active():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startEStopConfig(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEnabled(builder:flatbuffers.Builder, enabled:boolean) {
  builder.addFieldInt8(0, +enabled, +false);
}

static addGpioPin(builder:flatbuffers.Builder, gpioPin:number) {
  builder.addFieldInt8(1, gpioPin, 0);
}

static addActive(builder:flatbuffers.Builder, active:boolean) {
  builder.addFieldInt8(2, +active, +false);
}

static endEStopConfig(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEStopConfig(builder:flatbuffers.Builder, enabled:boolean, gpioPin:number, active:boolean):flatbuffers.Offset {
  EStopConfig.startEStopConfig(builder);
  EStopConfig.addEnabled(builder, enabled);
  EStopConfig.addGpioPin(builder, gpioPin);
  EStopConfig.addActive(builder, active);
  return EStopConfig.endEStopConfig(builder);
}
}
