// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LanConfig {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LanConfig {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLanConfig(bb:flatbuffers.ByteBuffer, obj?:LanConfig):LanConfig {
  return (obj || new LanConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLanConfig(bb:flatbuffers.ByteBuffer, obj?:LanConfig):LanConfig {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LanConfig()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Whether an API key is required for LAN endpoints
 */
apiKeyEnabled():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * API key for authenticating LAN requests (generated or user-set)
 */
apiKey():string|null
apiKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
apiKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startLanConfig(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addApiKeyEnabled(builder:flatbuffers.Builder, apiKeyEnabled:boolean) {
  builder.addFieldInt8(0, +apiKeyEnabled, +false);
}

static addApiKey(builder:flatbuffers.Builder, apiKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, apiKeyOffset, 0);
}

static endLanConfig(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLanConfig(builder:flatbuffers.Builder, apiKeyEnabled:boolean, apiKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  LanConfig.startLanConfig(builder);
  LanConfig.addApiKeyEnabled(builder, apiKeyEnabled);
  LanConfig.addApiKey(builder, apiKeyOffset);
  return LanConfig.endLanConfig(builder);
}
}
