// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * 6-byte MAC address (BSSID)
 */
export class MacAddress {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MacAddress {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

bytes(index: number):number|null {
    return this.bb!.readUint8(this.bb_pos + 0 + index);
}

static sizeOf():number {
  return 6;
}

static createMacAddress(builder:flatbuffers.Builder, bytes: number[]):flatbuffers.Offset {
  builder.prep(1, 6);

  for (let i = 5; i >= 0; --i) {
    builder.writeInt8((bytes?.[i] ?? 0));

  }

  return builder.offset();
}

}
