
name: build-filesystem
description: Builds the filesystem.
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}

    - uses: actions/cache@v3
      with:
        path: |
          ~/.platformio/platforms
          ~/.platformio/packages
          ~/.platformio/.cache
        key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini', 'requirements.txt') }}

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Download built captive portal
      uses: actions/download-artifact@v3
      with:
        name: captive-portal
        path: WebUI/build/

    - name: Build filesystem
      shell: bash
      run: pio run --target buildfs -e fs

    - name: Upload internal filesystem artifact
      uses: actions/upload-artifact@v3
      with:
        name: filesystem
        path: .pio/build/fs/littlefs.bin
        retention-days: 1
        if-no-files-found: error
