name: 'Request support for a new board'
description: "You'd like a prebuilt image for your board."
title: '[Board] '
labels: ['type: board-compatability']
projects: ['OpenShock/3']

body:

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: |
        To prevent wasting your or our time, please fill out the below checklist before continuing.
        Thanks for understanding!
      options:
        - label: 'I checked that there is no other open Board Request for this board.'
          required: true
        - label: 'I checked the [maintained boards list](https://wiki.openshock.org/hardware/boards/#fully-maintained) and this board is indeed not supported.'
          required: true
        - label: 'I accept that this issue may be closed if any of the above are found to be untrue.'
          required: true

  - type: markdown
    attributes:
      value: |
        # Board information

  - type: input
    id: board-name
    attributes:
      label: Board name
      description: The name of the board.
      placeholder: 'MyBrand XBoard v3, ...'
    validations:
      required: true

  - type: input
    id: board-chip
    attributes:
      label: Board MCU
      description: The MCU the board uses. Leave empty only if you don't know.
      placeholder: 'ESP32, ESP32-S3, ...'
    validations:
      required: false

  - type: input
    id: board-info-link
    attributes:
      label: Vendor board link
      description: Link to the description page for this board on the vendors' website.
      placeholder: 'E.g.: https://www.wemos.cc/en/latest/s3/s3_mini.html'
    validations:
      required: false

  - type: textarea
    id: board-purchase-links
    attributes:
      label: Purchase link(s)
      description: Put one or more links from where this board can be acquired.
      placeholder: |
        Examples:
        https://amazon.com/...
        https://aliexpress.com/...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Anything else?

  - type: textarea
    id: anything-else
    attributes:
      label: 'Other remarks'
    validations:
      required: false
