// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Sent when the auth token status changes (set, cleared, or validated on gateway connect)
 */
export class AccountLinkStatusEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AccountLinkStatusEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAccountLinkStatusEvent(bb:flatbuffers.ByteBuffer, obj?:AccountLinkStatusEvent):AccountLinkStatusEvent {
  return (obj || new AccountLinkStatusEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAccountLinkStatusEvent(bb:flatbuffers.ByteBuffer, obj?:AccountLinkStatusEvent):AccountLinkStatusEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AccountLinkStatusEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

linked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startAccountLinkStatusEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLinked(builder:flatbuffers.Builder, linked:boolean) {
  builder.addFieldInt8(0, +linked, +false);
}

static endAccountLinkStatusEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAccountLinkStatusEvent(builder:flatbuffers.Builder, linked:boolean):flatbuffers.Offset {
  AccountLinkStatusEvent.startAccountLinkStatusEvent(builder);
  AccountLinkStatusEvent.addLinked(builder, linked);
  return AccountLinkStatusEvent.endAccountLinkStatusEvent(builder);
}
}
