// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ShockerCommandList } from '../../../open-shock/serialization/common/shocker-command-list';


export enum LocalToHubMessagePayload {
  NONE = 0,
  Common_ShockerCommandList = 1
}

export function unionToLocalToHubMessagePayload(
  type: LocalToHubMessagePayload,
  accessor: (obj:ShockerCommandList) => ShockerCommandList|null
): ShockerCommandList|null {
  switch(LocalToHubMessagePayload[type]) {
    case 'NONE': return null; 
    case 'Common_ShockerCommandList': return accessor(new ShockerCommandList())! as ShockerCommandList;
    default: return null;
  }
}

export function unionListToLocalToHubMessagePayload(
  type: LocalToHubMessagePayload, 
  accessor: (index: number, obj:ShockerCommandList) => ShockerCommandList|null, 
  index: number
): ShockerCommandList|null {
  switch(LocalToHubMessagePayload[type]) {
    case 'NONE': return null; 
    case 'Common_ShockerCommandList': return accessor(index, new ShockerCommandList())! as ShockerCommandList;
    default: return null;
  }
}
