// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class OtaUpdateSetCheckIntervalCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OtaUpdateSetCheckIntervalCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

interval():number {
  return this.bb!.readUint16(this.bb_pos);
}

static sizeOf():number {
  return 2;
}

static createOtaUpdateSetCheckIntervalCommand(builder:flatbuffers.Builder, interval: number):flatbuffers.Offset {
  builder.prep(2, 2);
  builder.writeInt16(interval);
  return builder.offset();
}

}
