// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class OtaUpdateSetRequireManualApprovalCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OtaUpdateSetRequireManualApprovalCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOtaUpdateSetRequireManualApprovalCommand(bb:flatbuffers.ByteBuffer, obj?:OtaUpdateSetRequireManualApprovalCommand):OtaUpdateSetRequireManualApprovalCommand {
  return (obj || new OtaUpdateSetRequireManualApprovalCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOtaUpdateSetRequireManualApprovalCommand(bb:flatbuffers.ByteBuffer, obj?:OtaUpdateSetRequireManualApprovalCommand):OtaUpdateSetRequireManualApprovalCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OtaUpdateSetRequireManualApprovalCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

require():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startOtaUpdateSetRequireManualApprovalCommand(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRequire(builder:flatbuffers.Builder, require:boolean) {
  builder.addFieldInt8(0, +require, +false);
}

static endOtaUpdateSetRequireManualApprovalCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOtaUpdateSetRequireManualApprovalCommand(builder:flatbuffers.Builder, require:boolean):flatbuffers.Offset {
  OtaUpdateSetRequireManualApprovalCommand.startOtaUpdateSetRequireManualApprovalCommand(builder);
  OtaUpdateSetRequireManualApprovalCommand.addRequire(builder, require);
  return OtaUpdateSetRequireManualApprovalCommand.endOtaUpdateSetRequireManualApprovalCommand(builder);
}
}
