// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class WifiIpAddressChangedEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WifiIpAddressChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWifiIpAddressChangedEvent(bb:flatbuffers.ByteBuffer, obj?:WifiIpAddressChangedEvent):WifiIpAddressChangedEvent {
  return (obj || new WifiIpAddressChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWifiIpAddressChangedEvent(bb:flatbuffers.ByteBuffer, obj?:WifiIpAddressChangedEvent):WifiIpAddressChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WifiIpAddressChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ipAddress():string|null
ipAddress(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ipAddress(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startWifiIpAddressChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addIpAddress(builder:flatbuffers.Builder, ipAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ipAddressOffset, 0);
}

static endWifiIpAddressChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWifiIpAddressChangedEvent(builder:flatbuffers.Builder, ipAddressOffset:flatbuffers.Offset):flatbuffers.Offset {
  WifiIpAddressChangedEvent.startWifiIpAddressChangedEvent(builder);
  WifiIpAddressChangedEvent.addIpAddress(builder, ipAddressOffset);
  return WifiIpAddressChangedEvent.endWifiIpAddressChangedEvent(builder);
}
}
