// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { WifiScanStatus } from '../../../open-shock/serialization/types/wifi-scan-status';


export class WifiScanStatusMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WifiScanStatusMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

status():WifiScanStatus {
  return this.bb!.readUint8(this.bb_pos);
}

static sizeOf():number {
  return 1;
}

static createWifiScanStatusMessage(builder:flatbuffers.Builder, status: WifiScanStatus):flatbuffers.Offset {
  builder.prep(1, 1);
  builder.writeInt8(status);
  return builder.offset();
}

}
