// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class WifiNetworkSaveCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WifiNetworkSaveCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWifiNetworkSaveCommand(bb:flatbuffers.ByteBuffer, obj?:WifiNetworkSaveCommand):WifiNetworkSaveCommand {
  return (obj || new WifiNetworkSaveCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWifiNetworkSaveCommand(bb:flatbuffers.ByteBuffer, obj?:WifiNetworkSaveCommand):WifiNetworkSaveCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WifiNetworkSaveCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ssid():string|null
ssid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ssid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

password():string|null
password(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
password(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

connect():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startWifiNetworkSaveCommand(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSsid(builder:flatbuffers.Builder, ssidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ssidOffset, 0);
}

static addPassword(builder:flatbuffers.Builder, passwordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, passwordOffset, 0);
}

static addConnect(builder:flatbuffers.Builder, connect:boolean) {
  builder.addFieldInt8(2, +connect, +false);
}

static endWifiNetworkSaveCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWifiNetworkSaveCommand(builder:flatbuffers.Builder, ssidOffset:flatbuffers.Offset, passwordOffset:flatbuffers.Offset, connect:boolean):flatbuffers.Offset {
  WifiNetworkSaveCommand.startWifiNetworkSaveCommand(builder);
  WifiNetworkSaveCommand.addSsid(builder, ssidOffset);
  WifiNetworkSaveCommand.addPassword(builder, passwordOffset);
  WifiNetworkSaveCommand.addConnect(builder, connect);
  return WifiNetworkSaveCommand.endWifiNetworkSaveCommand(builder);
}
}
