name: build-staticfs
description: Builds the static filesystem partition and uploads it as an artifact
inputs:
  version:
    required: true
    description: 'Current firmware version'
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      if: ${{ !inputs.skip-checkout }}

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        path: |
          ~/.platformio/platforms
          ~/.platformio/packages
          ~/.platformio/.cache
        key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini', 'requirements.txt') }}

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Download built frontend
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: frontend
        path: frontend/build/

    - name: Build filesystem partition
      shell: bash
      run: pio run --target buildfs -e fs
      env:
        OPENSHOCK_FW_VERSION: ${{ inputs.version }}
        OPENSHOCK_FW_GIT_REF: ${{ github.ref }}
        OPENSHOCK_FW_GIT_COMMIT: ${{ github.sha }}
        OPENSHOCK_FW_BUILD_DATE: ${{ github.event.head_commit.timestamp }}

    - name: Rename partition binary
      shell: bash
      run: mv .pio/build/fs/littlefs.bin staticfs.bin

    - name: Upload internal filesystem artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: firmware_staticfs
        path: staticfs.bin
        retention-days: 1
        if-no-files-found: error
