name: build-firmware
description: Builds the firmware partitions and uploads them as an artifact
inputs:
  python-version:
    required: true
    description: 'Python version to use'
  board:
    required: true
    description: 'Board name to build'
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}

    - uses: actions/cache@v3
      with:
        path: |
          ~/.platformio/platforms
          ~/.platformio/packages
          ~/.platformio/.cache
        key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini', 'requirements.txt') }}

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install python dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Build firmware
      working-directory: .
      shell: bash
      run: pio run -e ${{ inputs.board }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware_build_${{ inputs.board }}
        path: .pio/build/${{ inputs.board }}/*.bin
        retention-days: 1
        if-no-files-found: error
