// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GatewayToHubMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsGatewayToHubMessage(buf []byte, offset flatbuffers.UOffsetT) *GatewayToHubMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GatewayToHubMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishGatewayToHubMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGatewayToHubMessage(buf []byte, offset flatbuffers.UOffsetT) *GatewayToHubMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GatewayToHubMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGatewayToHubMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GatewayToHubMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GatewayToHubMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GatewayToHubMessage) PayloadType() GatewayToHubMessagePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return GatewayToHubMessagePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GatewayToHubMessage) MutatePayloadType(n GatewayToHubMessagePayload) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *GatewayToHubMessage) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func GatewayToHubMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GatewayToHubMessageAddPayloadType(builder *flatbuffers.Builder, payloadType GatewayToHubMessagePayload) {
	builder.PrependByteSlot(0, byte(payloadType), 0)
}
func GatewayToHubMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func GatewayToHubMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
