// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Gateway

import "strconv"

type GatewayToHubMessagePayload byte

const (
	GatewayToHubMessagePayloadNONE               GatewayToHubMessagePayload = 0
	/// Ping message, should immediately be responded to with a pong
	GatewayToHubMessagePayloadPing               GatewayToHubMessagePayload = 1
	/// Trigger a specific action on the hub
	GatewayToHubMessagePayloadTrigger            GatewayToHubMessagePayload = 2
	/// Send a list of shocker commands to the hub
	GatewayToHubMessagePayloadShockerCommandList GatewayToHubMessagePayload = 3
	/// Request an OTA update to be performed
	GatewayToHubMessagePayloadOtaUpdateRequest   GatewayToHubMessagePayload = 4
)

var EnumNamesGatewayToHubMessagePayload = map[GatewayToHubMessagePayload]string{
	GatewayToHubMessagePayloadNONE:               "NONE",
	GatewayToHubMessagePayloadPing:               "Ping",
	GatewayToHubMessagePayloadTrigger:            "Trigger",
	GatewayToHubMessagePayloadShockerCommandList: "ShockerCommandList",
	GatewayToHubMessagePayloadOtaUpdateRequest:   "OtaUpdateRequest",
}

var EnumValuesGatewayToHubMessagePayload = map[string]GatewayToHubMessagePayload{
	"NONE":               GatewayToHubMessagePayloadNONE,
	"Ping":               GatewayToHubMessagePayloadPing,
	"Trigger":            GatewayToHubMessagePayloadTrigger,
	"ShockerCommandList": GatewayToHubMessagePayloadShockerCommandList,
	"OtaUpdateRequest":   GatewayToHubMessagePayloadOtaUpdateRequest,
}

func (v GatewayToHubMessagePayload) String() string {
	if s, ok := EnumNamesGatewayToHubMessagePayload[v]; ok {
		return s
	}
	return "GatewayToHubMessagePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
