// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HubToGatewayMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsHubToGatewayMessage(buf []byte, offset flatbuffers.UOffsetT) *HubToGatewayMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HubToGatewayMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishHubToGatewayMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHubToGatewayMessage(buf []byte, offset flatbuffers.UOffsetT) *HubToGatewayMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HubToGatewayMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHubToGatewayMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HubToGatewayMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HubToGatewayMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HubToGatewayMessage) PayloadType() HubToGatewayMessagePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return HubToGatewayMessagePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *HubToGatewayMessage) MutatePayloadType(n HubToGatewayMessagePayload) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *HubToGatewayMessage) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func HubToGatewayMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HubToGatewayMessageAddPayloadType(builder *flatbuffers.Builder, payloadType HubToGatewayMessagePayload) {
	builder.PrependByteSlot(0, byte(payloadType), 0)
}
func HubToGatewayMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func HubToGatewayMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
