// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"

	OpenShock__Serialization__Types "openshock.dev/mock-portal/fbs/OpenShock/Serialization/Types"
)

type OtaUpdateStarted struct {
	_tab flatbuffers.Table
}

func GetRootAsOtaUpdateStarted(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateStarted {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtaUpdateStarted{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtaUpdateStartedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtaUpdateStarted(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateStarted {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtaUpdateStarted{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtaUpdateStartedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtaUpdateStarted) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtaUpdateStarted) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtaUpdateStarted) UpdateId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OtaUpdateStarted) MutateUpdateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *OtaUpdateStarted) Version(obj *OpenShock__Serialization__Types.SemVer) *OpenShock__Serialization__Types.SemVer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OpenShock__Serialization__Types.SemVer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func OtaUpdateStartedStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OtaUpdateStartedAddUpdateId(builder *flatbuffers.Builder, updateId int32) {
	builder.PrependInt32Slot(0, updateId, 0)
}
func OtaUpdateStartedAddVersion(builder *flatbuffers.Builder, version flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(version), 0)
}
func OtaUpdateStartedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
