// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import "strconv"

type AccountLinkResultCode byte

const (
	AccountLinkResultCodeSuccess              AccountLinkResultCode = 0
	AccountLinkResultCodeCodeRequired         AccountLinkResultCode = 1
	AccountLinkResultCodeInvalidCodeLength    AccountLinkResultCode = 2
	AccountLinkResultCodeNoInternetConnection AccountLinkResultCode = 3
	AccountLinkResultCodeInvalidCode          AccountLinkResultCode = 4
	AccountLinkResultCodeRateLimited          AccountLinkResultCode = 5
	AccountLinkResultCodeInternalError        AccountLinkResultCode = 6
)

var EnumNamesAccountLinkResultCode = map[AccountLinkResultCode]string{
	AccountLinkResultCodeSuccess:              "Success",
	AccountLinkResultCodeCodeRequired:         "CodeRequired",
	AccountLinkResultCodeInvalidCodeLength:    "InvalidCodeLength",
	AccountLinkResultCodeNoInternetConnection: "NoInternetConnection",
	AccountLinkResultCodeInvalidCode:          "InvalidCode",
	AccountLinkResultCodeRateLimited:          "RateLimited",
	AccountLinkResultCodeInternalError:        "InternalError",
}

var EnumValuesAccountLinkResultCode = map[string]AccountLinkResultCode{
	"Success":              AccountLinkResultCodeSuccess,
	"CodeRequired":         AccountLinkResultCodeCodeRequired,
	"InvalidCodeLength":    AccountLinkResultCodeInvalidCodeLength,
	"NoInternetConnection": AccountLinkResultCodeNoInternetConnection,
	"InvalidCode":          AccountLinkResultCodeInvalidCode,
	"RateLimited":          AccountLinkResultCodeRateLimited,
	"InternalError":        AccountLinkResultCodeInternalError,
}

func (v AccountLinkResultCode) String() string {
	if s, ok := EnumNamesAccountLinkResultCode[v]; ok {
		return s
	}
	return "AccountLinkResultCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
