// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtaUpdateSetRequireManualApprovalCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsOtaUpdateSetRequireManualApprovalCommand(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateSetRequireManualApprovalCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtaUpdateSetRequireManualApprovalCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtaUpdateSetRequireManualApprovalCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtaUpdateSetRequireManualApprovalCommand(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateSetRequireManualApprovalCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtaUpdateSetRequireManualApprovalCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtaUpdateSetRequireManualApprovalCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtaUpdateSetRequireManualApprovalCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtaUpdateSetRequireManualApprovalCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtaUpdateSetRequireManualApprovalCommand) Require() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OtaUpdateSetRequireManualApprovalCommand) MutateRequire(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func OtaUpdateSetRequireManualApprovalCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OtaUpdateSetRequireManualApprovalCommandAddRequire(builder *flatbuffers.Builder, require bool) {
	builder.PrependBoolSlot(0, require, false)
}
func OtaUpdateSetRequireManualApprovalCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
