// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtaUpdateCheckForUpdatesCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsOtaUpdateCheckForUpdatesCommand(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateCheckForUpdatesCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtaUpdateCheckForUpdatesCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtaUpdateCheckForUpdatesCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtaUpdateCheckForUpdatesCommand(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateCheckForUpdatesCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtaUpdateCheckForUpdatesCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtaUpdateCheckForUpdatesCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtaUpdateCheckForUpdatesCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtaUpdateCheckForUpdatesCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtaUpdateCheckForUpdatesCommand) Channel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OtaUpdateCheckForUpdatesCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OtaUpdateCheckForUpdatesCommandAddChannel(builder *flatbuffers.Builder, channel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(channel), 0)
}
func OtaUpdateCheckForUpdatesCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
