// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtaUpdateHandleUpdateRequestCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsOtaUpdateHandleUpdateRequestCommand(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateHandleUpdateRequestCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtaUpdateHandleUpdateRequestCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtaUpdateHandleUpdateRequestCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtaUpdateHandleUpdateRequestCommand(buf []byte, offset flatbuffers.UOffsetT) *OtaUpdateHandleUpdateRequestCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtaUpdateHandleUpdateRequestCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtaUpdateHandleUpdateRequestCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtaUpdateHandleUpdateRequestCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtaUpdateHandleUpdateRequestCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtaUpdateHandleUpdateRequestCommand) Accept() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OtaUpdateHandleUpdateRequestCommand) MutateAccept(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func OtaUpdateHandleUpdateRequestCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OtaUpdateHandleUpdateRequestCommandAddAccept(builder *flatbuffers.Builder, accept bool) {
	builder.PrependBoolSlot(0, accept, false)
}
func OtaUpdateHandleUpdateRequestCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
