// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetEstopEnabledCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsSetEstopEnabledCommand(buf []byte, offset flatbuffers.UOffsetT) *SetEstopEnabledCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetEstopEnabledCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetEstopEnabledCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetEstopEnabledCommand(buf []byte, offset flatbuffers.UOffsetT) *SetEstopEnabledCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetEstopEnabledCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetEstopEnabledCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetEstopEnabledCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetEstopEnabledCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetEstopEnabledCommand) Enabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SetEstopEnabledCommand) MutateEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func SetEstopEnabledCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetEstopEnabledCommandAddEnabled(builder *flatbuffers.Builder, enabled bool) {
	builder.PrependBoolSlot(0, enabled, false)
}
func SetEstopEnabledCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
