// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WifiNetworkForgetCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsWifiNetworkForgetCommand(buf []byte, offset flatbuffers.UOffsetT) *WifiNetworkForgetCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WifiNetworkForgetCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishWifiNetworkForgetCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWifiNetworkForgetCommand(buf []byte, offset flatbuffers.UOffsetT) *WifiNetworkForgetCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WifiNetworkForgetCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWifiNetworkForgetCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WifiNetworkForgetCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WifiNetworkForgetCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WifiNetworkForgetCommand) Ssid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WifiNetworkForgetCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WifiNetworkForgetCommandAddSsid(builder *flatbuffers.Builder, ssid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ssid), 0)
}
func WifiNetworkForgetCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
