// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WifiGotIpEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsWifiGotIpEvent(buf []byte, offset flatbuffers.UOffsetT) *WifiGotIpEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WifiGotIpEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishWifiGotIpEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWifiGotIpEvent(buf []byte, offset flatbuffers.UOffsetT) *WifiGotIpEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WifiGotIpEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWifiGotIpEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WifiGotIpEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WifiGotIpEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WifiGotIpEvent) Ip() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WifiGotIpEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WifiGotIpEventAddIp(builder *flatbuffers.Builder, ip flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ip), 0)
}
func WifiGotIpEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
