// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Local

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WifiLostIpEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsWifiLostIpEvent(buf []byte, offset flatbuffers.UOffsetT) *WifiLostIpEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WifiLostIpEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishWifiLostIpEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWifiLostIpEvent(buf []byte, offset flatbuffers.UOffsetT) *WifiLostIpEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WifiLostIpEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWifiLostIpEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WifiLostIpEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WifiLostIpEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WifiLostIpEvent) Ip() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WifiLostIpEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WifiLostIpEventAddIp(builder *flatbuffers.Builder, ip flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ip), 0)
}
func WifiLostIpEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
