name: cdn-upload-version-info
description: Uploads version specific info to CDN
inputs:
  fw-version:
    description: Firmware version
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true
  boards:
    description: 'List of boards, separated by newlines'
    required: true

runs:
  using: composite
  steps:
    - name: Create boards.txt
      shell: bash
      run: |
        echo -e '${{ inputs.boards }}' >> boards.txt

    - name: Upload artifacts to CDN
      shell: bash
      run: |
        mkdir -p upload
        mv boards.txt upload/
        rclone copy upload 'cdn:${{ inputs.fw-version }}/${{ inputs.board }}/'
