// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CaptivePortalConfig } from '../../open-shock/serialization/captive-portal-config';
import { ShockerCommandList } from '../../open-shock/serialization/shocker-command-list';


export enum ServerToDeviceMessagePayload {
  NONE = 0,
  ShockerCommandList = 1,
  CaptivePortalConfig = 2
}

export function unionToServerToDeviceMessagePayload(
  type: ServerToDeviceMessagePayload,
  accessor: (obj:CaptivePortalConfig|ShockerCommandList) => CaptivePortalConfig|ShockerCommandList|null
): CaptivePortalConfig|ShockerCommandList|null {
  switch(ServerToDeviceMessagePayload[type]) {
    case 'NONE': return null; 
    case 'ShockerCommandList': return accessor(new ShockerCommandList())! as ShockerCommandList;
    case 'CaptivePortalConfig': return accessor(new CaptivePortalConfig())! as CaptivePortalConfig;
    default: return null;
  }
}

export function unionListToServerToDeviceMessagePayload(
  type: ServerToDeviceMessagePayload, 
  accessor: (index: number, obj:CaptivePortalConfig|ShockerCommandList) => CaptivePortalConfig|ShockerCommandList|null, 
  index: number
): CaptivePortalConfig|ShockerCommandList|null {
  switch(ServerToDeviceMessagePayload[type]) {
    case 'NONE': return null; 
    case 'ShockerCommandList': return accessor(index, new ShockerCommandList())! as ShockerCommandList;
    case 'CaptivePortalConfig': return accessor(index, new CaptivePortalConfig())! as CaptivePortalConfig;
    default: return null;
  }
}
