#include "OpenShock.h"

// The one translation unit that sees the firmware version and git commit.
//
// openshock_version.h is regenerated on every build (see the root CMakeLists.txt), so
// everything including it recompiles whenever the commit changes. Keeping that to this
// file, and exposing the result as a linker symbol, means a new commit rebuilds one
// object instead of every object in the project.
#include "openshock_version.h"

#ifndef OPENSHOCK_FW_VERSION
#error "OPENSHOCK_FW_VERSION must be defined (generated by scripts/gen_env_header.py)"
#endif

// Allow the user agent to be overridden through compiler flags; otherwise build it from
// the hostname, version, board and chip.
#ifndef OPENSHOCK_FW_USERAGENT
#define OPENSHOCK_FW_USERAGENT CONFIG_OPENSHOCK_FW_HOSTNAME "/" OPENSHOCK_FW_VERSION " (ESP-IDF; " OPENSHOCK_FW_BOARD "; " OPENSHOCK_FW_CHIP "; Espressif)"
#endif

namespace OpenShock::Constants {
  const char* const FW_USERAGENT = OPENSHOCK_FW_USERAGENT;
}  // namespace OpenShock::Constants
