#include "OpenShock.h"

#include "SemVer.h"

// The one translation unit that sees the firmware version and git commit.
//
// openshock_version.h is regenerated on every build (see the root CMakeLists.txt), so
// everything including it recompiles whenever the commit changes. Keeping that to this
// file, and exposing the result as a linker symbol, means a new commit rebuilds one
// object instead of every object in the project.
#include "openshock_version.h"

#if !defined(OPENSHOCK_FW_VERSION) || !defined(OPENSHOCK_FW_VERSION_MAJOR) || !defined(OPENSHOCK_FW_VERSION_MINOR) || !defined(OPENSHOCK_FW_VERSION_PATCH) || !defined(OPENSHOCK_FW_GIT_COMMIT)
#error "openshock_version.h is incomplete (generated by scripts/gen_env_header.py)"
#endif
#ifndef OPENSHOCK_FW_VERSION_PRERELEASE
#define OPENSHOCK_FW_VERSION_PRERELEASE ""
#endif
#ifndef OPENSHOCK_FW_VERSION_BUILD
#define OPENSHOCK_FW_VERSION_BUILD ""
#endif

// Allow the user agent to be overridden through compiler flags; otherwise build it from
// the hostname, version, board and chip.
#ifndef OPENSHOCK_FW_USERAGENT
#define OPENSHOCK_FW_USERAGENT CONFIG_OPENSHOCK_FW_HOSTNAME "/" OPENSHOCK_FW_VERSION " (ESP-IDF; " OPENSHOCK_FW_BOARD "; " OPENSHOCK_FW_CHIP "; Espressif)"
#endif

namespace OpenShock::Constants {
  const char* const FW_USERAGENT  = OPENSHOCK_FW_USERAGENT;
  const char* const FW_VERSION    = OPENSHOCK_FW_VERSION;
  const char* const FW_GIT_COMMIT = OPENSHOCK_FW_GIT_COMMIT;

  const OpenShock::SemVer& FirmwareVersion()
  {
    static const OpenShock::SemVer version(OPENSHOCK_FW_VERSION_MAJOR, OPENSHOCK_FW_VERSION_MINOR, OPENSHOCK_FW_VERSION_PATCH, OPENSHOCK_FW_VERSION_PRERELEASE, OPENSHOCK_FW_VERSION_BUILD);
    return version;
  }
}  // namespace OpenShock::Constants
