// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ReadyMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadyMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

poggies():boolean {
  return !!this.bb!.readInt8(this.bb_pos);
}

static sizeOf():number {
  return 1;
}

static createReadyMessage(builder:flatbuffers.Builder, poggies: boolean):flatbuffers.Offset {
  builder.prep(1, 1);
  builder.writeInt8(Number(Boolean(poggies)));
  return builder.offset();
}

}
