// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SavedNetworkRemovedEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SavedNetworkRemovedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSavedNetworkRemovedEvent(bb:flatbuffers.ByteBuffer, obj?:SavedNetworkRemovedEvent):SavedNetworkRemovedEvent {
  return (obj || new SavedNetworkRemovedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSavedNetworkRemovedEvent(bb:flatbuffers.ByteBuffer, obj?:SavedNetworkRemovedEvent):SavedNetworkRemovedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SavedNetworkRemovedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ssid():string|null
ssid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ssid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSavedNetworkRemovedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSsid(builder:flatbuffers.Builder, ssidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ssidOffset, 0);
}

static endSavedNetworkRemovedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSavedNetworkRemovedEvent(builder:flatbuffers.Builder, ssidOffset:flatbuffers.Offset):flatbuffers.Offset {
  SavedNetworkRemovedEvent.startSavedNetworkRemovedEvent(builder);
  SavedNetworkRemovedEvent.addSsid(builder, ssidOffset);
  return SavedNetworkRemovedEvent.endSavedNetworkRemovedEvent(builder);
}
}
