// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { WifiNetwork } from '../../../open-shock/serialization/local/wifi-network.js';


export class WifiNetworkRemovedEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WifiNetworkRemovedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWifiNetworkRemovedEvent(bb:flatbuffers.ByteBuffer, obj?:WifiNetworkRemovedEvent):WifiNetworkRemovedEvent {
  return (obj || new WifiNetworkRemovedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWifiNetworkRemovedEvent(bb:flatbuffers.ByteBuffer, obj?:WifiNetworkRemovedEvent):WifiNetworkRemovedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WifiNetworkRemovedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

network(obj?:WifiNetwork):WifiNetwork|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new WifiNetwork()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startWifiNetworkRemovedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNetwork(builder:flatbuffers.Builder, networkOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, networkOffset, 0);
}

static endWifiNetworkRemovedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWifiNetworkRemovedEvent(builder:flatbuffers.Builder, networkOffset:flatbuffers.Offset):flatbuffers.Offset {
  WifiNetworkRemovedEvent.startWifiNetworkRemovedEvent(builder);
  WifiNetworkRemovedEvent.addNetwork(builder, networkOffset);
  return WifiNetworkRemovedEvent.endWifiNetworkRemovedEvent(builder);
}
}
