name: merge-partitions
description: Merges multiple partitions into a single flashable binary
inputs:
  version:
    description: 'Version of the firmware'
    required: true
  board:
    description: 'Board name to merge partitions for'
    required: true
  skip-checkout:
    description: 'If true, skips checkout'
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      if: ${{ !inputs.skip-checkout }}
      with:
        sparse-checkout: |
          scripts
          boards
          chips

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Download static filesystem partition
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: firmware_staticfs

    - name: Download firmware partitions
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: firmware_build_${{ inputs.board }}

    - name: Merge partitions
      shell: bash
      run: |
        python scripts/merge_image.py ${{ inputs.board }}
        mv merged.bin OpenShock_${{ inputs.board }}_${{ inputs.version }}.bin

    - name: Upload merged firmware binary
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: firmware_merged_${{ inputs.board }}
        path: OpenShock_${{ inputs.board }}_*.bin
        retention-days: 7
        if-no-files-found: error
