name: build-frontend
description: Builds the frontend and uploads it as an artifact
inputs:
  skip-checkout:
    description: 'If true, skips checkout'
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}
      with:
        sparse-checkout: |
          frontend
        path: ${{ github.repository }}

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        cache-dependency-path: ./frontend/pnpm-lock.yaml

    - name: Install dependencies
      working-directory: ./frontend
      shell: bash
      run: pnpm install --frozen-lockfile --strict-peer-dependencies

    - name: Check
      working-directory: ./frontend
      shell: bash
      run: pnpm run check

    # FIXME: Playwirght is not working: Error: browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell
    #    - name: Install playwright
    #      working-directory: ./frontend
    #      shell: bash
    #      run: pnpx playwright install --with-deps

    - name: Test
      working-directory: ./frontend
      shell: bash
      run: pnpm test:unit # TODO: Change back to pnpm test when playwright is working

    - name: Build
      working-directory: ./frontend
      shell: bash
      run: pnpm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: frontend/build/*
        retention-days: 1
        if-no-files-found: error
