name: build-frontend
description: Builds the frontend and uploads it as an artifact

runs:
  using: composite
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: ./frontend/package.json

    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      name: Install pnpm
      with:
          cache: true
          cache_dependency_path: ./frontend/pnpm-lock.yaml
          package_json_file: ./frontend/package.json
          run_install: |
            - recursive: true
              cwd: ./frontend
              args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Check
      working-directory: ./frontend
      shell: bash
      run: pnpm run check

    # FIXME: Playwirght is not working: Error: browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell
    #    - name: Install playwright
    #      working-directory: ./frontend
    #      shell: bash
    #      run: pnpx playwright install --with-deps

    - name: Test
      working-directory: ./frontend
      shell: bash
      run: pnpm test:unit # TODO: Change back to pnpm test when playwright is working

    - name: Build
      working-directory: ./frontend
      shell: bash
      run: pnpm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: frontend
        path: frontend/build/*
        retention-days: 1
        if-no-files-found: error
